version: "3.7"
services:
  adversarial:
    build:
      context: .
      dockerfile: Dockerfile-mod
    network_mode: host
    environment:
      - MUJOCO_KEY=www.roboti.us/file/mjkey.txt
    volumes:
      - ./src:/adversarial-policies/src
      - ./data:/adversarial-policies/data
    stdin_open: true
    tty: true
